language: php

php:
  - 8.0
  - 8.1
  - 8.2
  # https://github.com/sebastianbergmann/phpunit/issues/2581
  # - hhvm

before_script:
  - composer install --no-dev

script:
  - phpunit --configuration phpunit.xml --coverage-text
